require("babel-polyfill");

const config = require("./config");
const { getUser, getTenant, getAppList, baseUrl } = require("./comm");

const link = document.createElement("link");
link.rel = "stylesheet";
link.href = `${baseUrl}/resources/autogenerated/qlik-styles.css`;
document.head.appendChild(link);

const script = document.createElement("script");
script.src = `${baseUrl}/resources/assets/external/requirejs/require.js`;
script.onload = async () => {
  requirejs.config({
    baseUrl: baseUrl + "/resources",
    webIntegrationId: config.webIntegrationId,
  });

  // build a single-sign on URL and return back here once completed:
  const loginUrl = new URL(`${baseUrl}/login`);
  loginUrl.searchParams.append("returnto", location.href);
  loginUrl.searchParams.append(
    "qlik-web-integration-id",
    config.webIntegrationId
  );

  const loginBtn = document.querySelector("#login");
  loginBtn.addEventListener("click", () => {
    location.href = loginUrl;
  });

  const logoutBtn = document.querySelector("#logout");
  logoutBtn.addEventListener("click", () => {
    location.href = new URL(`${baseUrl}/logout`);
  });

  const [user, tenant] = await Promise.all([getUser(), getTenant()]);
  if (user || tenant) {
    loginBtn.disabled = true;
    logoutBtn.disabled = false;
    document.querySelector(".logged_in").style.opacity = 0;
    document.querySelector(".logged_out").style.opacity = 1;
    document.querySelector("#user").innerHTML = user.name;
    document.querySelector("#tenant").innerHTML = tenant.name;
    initMashup();
  } else {
    loginBtn.disabled = false;
    logoutBtn.disabled = true;
    document.querySelector(".logged_in").style.opacity = 1;
    document.querySelector(".logged_out").style.opacity = 0;
  }
};

document.body.appendChild(script);

function renderError(error) {
  document.querySelector(
    "#QV01"
  ).innerHTML = `Failed to render charts: <pre><code>${
    error.error || error.stack || error.message || error
  }</code></pre>`;
}

async function initMashup() {
  const list = await getAppList();
  const ulElement = document.createElement("ul");

  list.data.forEach((appItem) => {
    const liElement = document.createElement("li");
    liElement.innerHTML = `<b>${appItem.name}</b> - ${appItem.resourceId}`;
    ulElement.appendChild(liElement);
  });
  document.querySelector("#app_list").appendChild(ulElement);

  const appIds = list.data
    .filter((appItem) => appItem.name.indexOf("drug") !== -1)
    .map((appItem) => appItem.resourceId);

  requirejs(["js/qlik"], async (qlik) => {
    const app = qlik.openApp(appIds.length ? appIds[0] : config.appId, config);
    app.on("error", renderError);
    app.getObject("CurrentSelections", "CurrentSelections");

    try {
      //Create visualizations
      const vis = await app.visualization.create(
        "piechart",
        [
          {
            qDef: {
              qGrouping: "N",
              qFieldDefs: ["state_name"],
              qFieldLabels: [],
            },
          },
          {
            qDef: {
              qLabel: "",
              qDescription: "",
              qTags: [],
              qGrouping: "N",
              qDef: "rand()",
            },
          },
        ],
        {
          title: "Total drug cases per continent",
        }
      );

      vis.show("QV01");

      /*-----------------------------------------------------------------------------------------------------------------------
     NOK - https://help.qlik.com/en-US/sense-developer/May2022/Subsystems/APIs/Content/Sense_ClientAPIs/CapabilityAPIs/VisualizationAPI/exportPdf-method.htm
     RETURNS A 400 BAD REQUEST
    -------------------------------------------------------------------------------------------------------------------------*/

      var settings = {
        documentSize: "a4",
        aspectRatio: 2,
        orientation: "landscape",
      };

      vis.exportPdf(settings).then(function (result) {
        console.log("PDF download link: ", result);
      });

      /*-----------------------------------------------------------------------------------------------------------------------
     NOK - https://help.qlik.com/en-US/sense-developer/May2022/Subsystems/APIs/Content/Sense_ClientAPIs/CapabilityAPIs/VisualizationAPI/exportData-method.htm
     RETURNS A 404 CHART NOT FOUND
    -------------------------------------------------------------------------------------------------------------------------*/

      vis.exportData({ format: "CSV_T", state: "A" }).then(function (link) {
        window.open(link);
      });

      /*-----------------------------------------------------------------------------------------------------------------------
    OK  https://help.qlik.com/en-US/sense-developer/May2022/Subsystems/APIs/Content/Sense_ClientAPIs/CapabilityAPIs/VisualizationAPI/exportImg-method.htm
    -------------------------------------------------------------------------------------------------------------------------*/
      var settings = {
        format: "png",
        height: 600,
        width: 600,
      };
      vis.exportImg(settings).then(function (result) {
        console.log("Image download link: ", result);
      });
    } catch (error) {
      renderError(error);
    }
  });
}
